openapi: 3.0.3
info:
  description: API for managing safety equipment.
  version: 0.0.1
  title: Safety API
servers:
  - url: SERVER_URL
security:
  - ApiKeyAuth: []
paths:
  /images:
    get:
      summary: List objects.
      description: Retrieve a page of objects from the server.
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  Images:
                    type: array
                    items:
                      $ref: "#/components/schemas/ListOfImages"
    post:
      summary: Creates a new object.
      description: Creates a new object.
      requestBody:
        description: The object to create.
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Image"
      responses:
        "201":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"
  /images/{id}:
    get:
      summary: Retrieve object.
      description: Retrieve a single object.
      parameters:
        - name: id
          in: path
          required: true
          description: Unique identifier of the desired object.
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"
        "404":
          description: Object was not found.
    put:
      summary: Update object.
      description: Update a single object.
      parameters:
        - name: id
          in: path
          required: true
          description: Unique identifier of the desired object.
          schema:
            type: string
      requestBody:
        description: The object to update.
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Image"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"
        "404":
          description: Object was not found.
    delete:
      summary: Delete object.
      description: Delete a single object.
      parameters:
        - name: id
          in: path
          required: true
          description: Unique identifier of the desired object.
          schema:
            type: string
      responses:
        "200":
          description: Successful response
        "404":
          description: Object was not found.
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: x-apikey
      in: header
  schemas:
    Image:
      title: Image
      type: object
      properties:
        id:
          description: The id of the object
          type: string
          example: hu32hu3
        dateTime:
          description: The date-time of the object
          type: string
          example: 8/9/2023 9:38:51 AM
        description:
          description: The text of the object
          type: string
          example: Example description
        location:
          description: The location of the object
          type: string
          example: Paris, France
        image:
          description: An image in base64 format
          type: string
        looksSafe:
          description: An evaluation by the image LLM if the image looks safe or not
          type: string
          example: True
        generatedCaption:
          description: A generated caption by the LLM of the iamge
          type: string
          example: A very safe looking warehouse
    ListOfImages:
      title: List of objects
      type: array
      items:
        $ref: "#/components/schemas/Image"
